server:
  port: ${test.eureka.server.port}    # 指定该Eureka实例的端⼝

spring:
  profiles: test
  security:
      user:
        name: admin
        password: ${SECURITY_USER_PASSWORD:admin1234}

eureka:
  environment: test
  datacenter: linux
  server:
    enable-self-preservation: true  # 关闭自我保护
  instance:
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
#    prefer-ip-address: true   # 这个设置成true后， unavailable-replicas '异常'
    hostname: ${test.eureka.hostname}    # 指定该Eureka实例的主机名
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registerWithEureka: false  # 单机模式 设置为false
    fetchRegistry: false       # 单机模式 设置为false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${test.eureka.hostname}:${test.eureka.server.port}/eureka/


